# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x02pb\"\x12\n\x03req\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x13\n\x04rply\x12\x0b\n\x03msg\x18\x01 \x01(\t2 \n\x04GRPC\x12\x18\n\x03Req\x12\x07.pb.req\x1a\x08.pb.rplyB\x07Z\x05./;pbb\x06proto3')



_REQ = DESCRIPTOR.message_types_by_name['req']
_RPLY = DESCRIPTOR.message_types_by_name['rply']
req = _reflection.GeneratedProtocolMessageType('req', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.req)
  })
_sym_db.RegisterMessage(req)

rply = _reflection.GeneratedProtocolMessageType('rply', (_message.Message,), {
  'DESCRIPTOR' : _RPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:pb.rply)
  })
_sym_db.RegisterMessage(rply)

_GRPC = DESCRIPTOR.services_by_name['GRPC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./;pb'
  _REQ._serialized_start=18
  _REQ._serialized_end=36
  _RPLY._serialized_start=38
  _RPLY._serialized_end=57
  _GRPC._serialized_start=59
  _GRPC._serialized_end=91
# @@protoc_insertion_point(module_scope)
